---
title: 'ESM 244 Lab 4 Part 2: Time Series Data Wrangling'
author: "Carlos Simms"
date: "1/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse) # Default.
library(here) # To create file paths to data within different folders.
library(lubridate) # To mutate date formats.
library(tsibble) # To make time series tibbles.
library(feasts) # To wrangle and work with time series data.
library(slider) # To find moving averages and specify windows of interest.
```

### Read in the data:

```{r}
toolik <- read_csv(here("data", 
                        "toolikweather.csv"))
```

### Convert this into a 'tsibble':

```{r}
toolik_ts <- toolik %>% 
  mutate(date = mdy(date)) %>% 
  as_tsibble(key = NULL, 
             index = date) # To read dates as time series information.

ggplot(data = toolik_ts, 
       aes(x = date, 
           y = mean_airtemp)) + 
  geom_line()
```

### Use the 'index_by()' function to aggregate time series information by intervals we specify:

```{r}
# Aggregate by month:

toolik_month <- toolik_ts %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% # To aggregate the information by year and month, and then to specify it across the entire data set.
  summarize(monthly_mean_temp = mean(mean_airtemp, 
                                     na.rm = TRUE))

ggplot(data = toolik_month, 
       aes(x = yr_mo, 
           y = monthly_mean_temp)) + 
  geom_line() + 
  facet_wrap(~month(yr_mo, 
             label = TRUE))

# Aggregate by week:

toolik_weekly <- toolik_ts %>% 
  index_by(weekly = ~yearweek(.)) %>% # To aggregate the information by year and week, and then to specify it across the entire data set.
  summarize(weekly_airtemp = mean(mean_airtemp, 
                                  na.rm = TRUE)) # Adding "min_airtemp = min(mean_airtemp)" to this code does not Knit well in R Cloud.

head(toolik_weekly)
```

### Filtering time series - using 'filter_index()' to specify ranges of time series to keep or exclude:

```{r}
toolik_ts %>% 
  filter_index("2000-06" ~ "2001-10")

toolik_ts %>% 
  filter_index("2006-04-10" ~ "2006-05-15")
```

### Seasonplots:

```{r}
# Seasonal series plots:

toolik_ts %>% 
  filter(year(date) > 2014) %>% 
  gg_season(y = mean_airtemp)

toolik_month %>% 
  gg_season(y = monthly_mean_temp) + 
  theme_light()

# Seasonal subseries plots:

toolik_month %>% 
  gg_subseries(monthly_mean_temp)
```

### Find the moving average using the 'slidder' package:

```{r}
# A general example:

set.seed(2021)
test <- rnorm(n = 100, 
              mean = 40, 
              sd = 10)

slide(test, 
      ~.x, 
      .before = 2, 
      .after = 2)

# An example with the 'toolik' data:

roll_toolik_15 <- toolik_ts %>% 
  mutate(ma_15d = as.numeric(slide(toolik_ts$mean_airtemp, 
                                   mean, 
                                   .before = 7, 
                                   .after = 7)))

ggplot() + 
  geom_line(data = toolik_ts, 
            aes(x = date, 
                y = mean_airtemp), 
            size = 0.2, 
            color = "grey") + # Raw data series.
  geom_line(data = roll_toolik_15, 
            aes(x = date, 
                y = ma_15d)) + # Specified data series (graphing both for juxtaposition).
  theme_minimal()
```

### Create the ACF:

```{r}
toolik_ts %>% 
  feasts::ACF(mean_airtemp) %>% 
  autoplot() # To automatically plot data.

toolik_month %>% 
  ACF(monthly_mean_temp) %>% 
  autoplot()
```

### Decomposition by STL:

```{r}
toolik_dec <- toolik_month %>% 
  model(STL(monthly_mean_temp ~ season(window = Inf)))

components(toolik_dec) %>% 
  autoplot()
```

END
